<template>
  <div class="max-w-3xl mx-auto px-6">

    <div class="mb-12">
      <p class="text-primary text-xs font-semibold tracking-widest uppercase mb-3">Legal</p>
      <h1 class="text-4xl font-bold text-white mb-4">Privacy Policy</h1>
      <p class="text-gray-500 text-sm">Last updated: April 29, 2026</p>
    </div>

    <div class="space-y-10 text-gray-400 leading-relaxed">

      <section v-for="section in sections" :key="section.title" class="space-y-3">
        <h2 class="text-xl font-semibold text-white">{{ section.title }}</h2>
        <p v-for="(para, i) in section.paragraphs" :key="i">{{ para }}</p>
        <ul v-if="section.items" class="list-disc list-inside space-y-1 text-gray-500 pl-2">
          <li v-for="item in section.items" :key="item">{{ item }}</li>
        </ul>
      </section>

      <section class="space-y-3">
        <h2 class="text-xl font-semibold text-white">Contact</h2>
        <p>
          For privacy-related questions or requests, contact us at
          <a href="mailto:privacy@vibevista.com" class="text-primary hover:underline">privacy@vibevista.com</a>.
        </p>
      </section>

    </div>
  </div>
</template>

<script setup lang="ts">
const sections = [
  {
    title: '1. Introduction',
    paragraphs: [
      'VibeVista ("we", "our", or "us") is committed to protecting your privacy. This Privacy Policy explains what information we collect, how we use it, and your rights in relation to it. By using VibeVista, you agree to the practices described in this policy.',
    ],
  },
  {
    title: '2. Information We Collect',
    paragraphs: [
      'We collect information you provide directly, information generated by your use of the platform, and information from third-party services where applicable.',
    ],
    items: [
      'Account Information: Your name, username, email address, and password when you register.',
      'Profile Information: Profile photo, bio, and any other information you choose to add to your public profile.',
      'Creator Profile Information: Headline, bio, website, bank name, account number, and account name provided when setting up a creator profile for payout purposes.',
      'Payment Information: Transaction amounts, Paystack payment references, and enrollment financial records. We do not store your card details — all card processing is handled by Paystack.',
      'Payout Information: Bank account details, Paystack subaccount codes, and transfer references associated with creator payouts.',
      'Learning Activity: Courses you enroll in, lessons you complete, progress data, and reviews you submit.',
      'Course Content: If you are a creator, the videos, text, attachments, and other materials you upload to the platform.',
      'Usage Data: Pages visited, features used, time spent, device type, browser, IP address, and referring URLs.',
      'Communications: Messages you send to our support team or through any in-platform communication features.',
    ],
  },
  {
    title: '3. How We Use Your Information',
    paragraphs: [
      'We use the information we collect to:',
    ],
    items: [
      'Provide, operate, and improve the VibeVista platform',
      'Process course enrollments and payments via Paystack',
      'Facilitate creator payouts to registered bank accounts',
      'Track and display your learning progress and course completion',
      'Send transactional notifications such as enrollment confirmations, course approvals, and payout updates',
      'Verify creator profiles and review course content before publication',
      'Detect and prevent fraud, abuse, and violations of our Terms and Conditions',
      'Respond to support requests and resolve disputes',
      'Comply with applicable legal obligations',
      'Send product updates and promotional communications where you have opted in',
    ],
  },
  {
    title: '4. Sharing Your Information',
    paragraphs: [
      'We do not sell your personal information. We share your data only in the following circumstances:',
    ],
    items: [
      'Paystack: We share payment and payout information with Paystack to process transactions and creator withdrawals. This includes your email address for payment initialisation, and creator bank account details and recipient codes for transfer processing. Paystack\'s privacy policy is available at paystack.com/privacy.',
      'Mux: If you are a creator, video content you upload is processed and stored by Mux for transcoding and streaming. Mux handles video asset IDs and playback on our behalf.',
      'Cloudinary: File attachments uploaded to course lessons are stored and served via Cloudinary.',
      'Service Providers: We may share data with other trusted third-party providers who assist us in operating the platform, subject to confidentiality obligations.',
      'Legal Requirements: We may disclose information where required by law, court order, or to protect the rights and safety of VibeVista, our users, or the public.',
      'Business Transfers: In the event of a merger, acquisition, or sale of assets, your information may be transferred to the successor entity.',
    ],
  },
  {
    title: '5. Data Retention',
    paragraphs: [
      'We retain your personal information for as long as your account is active or as needed to provide you with our services. If you delete your account, we will remove your personal data within 30 days, except where retention is required by law or for legitimate business purposes such as resolving disputes or preventing fraud.',
      'Creator payout records and enrollment financial data are retained for a minimum of 7 years for accounting and regulatory compliance purposes, even after account deletion.',
    ],
  },
  {
    title: '6. Cookies & Tracking',
    paragraphs: [
      'We use cookies and similar tracking technologies to maintain your session, remember your preferences, and analyse usage patterns. You can control cookie settings through your browser, though disabling cookies may affect platform functionality.',
    ],
  },
  {
    title: '7. Data Security',
    paragraphs: [
      'We implement industry-standard security measures to protect your information, including encrypted connections (HTTPS), hashed passwords, and access controls. However, no method of transmission or storage is completely secure, and we cannot guarantee absolute security.',
      'Creator bank account details and Paystack codes are stored with restricted access and are only used for the purpose of processing payouts.',
    ],
  },
  {
    title: '8. Your Rights',
    paragraphs: [
      'Depending on your jurisdiction, you may have the following rights regarding your personal data:',
    ],
    items: [
      'Access: Request a copy of the personal data we hold about you.',
      'Correction: Request that we correct inaccurate or incomplete information.',
      'Deletion: Request that we delete your personal data, subject to legal retention requirements.',
      'Portability: Request your data in a structured, machine-readable format.',
      'Objection: Object to the processing of your data for marketing purposes at any time.',
      'Withdrawal of Consent: Where processing is based on consent, you may withdraw it at any time without affecting the lawfulness of prior processing.',
    ],
  },
  {
    title: '9. Children\'s Privacy',
    paragraphs: [
      'VibeVista is not directed at children under the age of 13. We do not knowingly collect personal information from children. If you believe a child has provided us with personal data, please contact us and we will take steps to remove the information promptly.',
    ],
  },
  {
    title: '10. Third-Party Links',
    paragraphs: [
      'The platform may contain links to third-party websites or services, including creator websites listed on their profiles. We are not responsible for the privacy practices of third-party sites and encourage you to review their privacy policies.',
    ],
  },
  {
    title: '11. Changes to This Policy',
    paragraphs: [
      'We may update this Privacy Policy from time to time. We will notify you of significant changes via email or an in-app notice. Continued use of VibeVista after changes take effect constitutes acceptance of the revised policy.',
    ],
  },
]
</script>
