<template>
  <div class="max-w-3xl mx-auto px-6">

    <div class="mb-12">
      <p class="text-primary text-xs font-semibold tracking-widest uppercase mb-3">Legal</p>
      <h1 class="text-4xl font-bold text-white mb-4">Privacy Policy</h1>
      <p class="text-gray-500 text-sm">Last updated: April 29, 2026</p>
    </div>

    <div class="space-y-10 text-gray-400 leading-relaxed">

      <section v-for="section in sections" :key="section.title" class="space-y-3">
        <h2 class="text-xl font-semibold text-white">{{ section.title }}</h2>
        <p v-for="(para, i) in section.paragraphs" :key="i">{{ para }}</p>
        <ul v-if="section.items" class="list-disc list-inside space-y-1 text-gray-500 pl-2">
          <li v-for="item in section.items" :key="item">{{ item }}</li>
        </ul>
      </section>

      <section class="space-y-3">
        <h2 class="text-xl font-semibold text-white">Contact</h2>
        <p>
          For privacy-related questions or requests, contact us at
          <a href="mailto:privacy@vibevista.com" class="text-primary hover:underline">privacy@vibevista.com</a>.
        </p>
      </section>

    </div>
  </div>
</template>

<script setup lang="ts">
const sections = [
  {
    title: '1. Introduction',
    paragraphs: [
      'VibeVista ("we", "our", or "us") is committed to protecting your privacy. This Privacy Policy explains what information we collect, how we use it, and your rights in relation to it. By using VibeVista, you agree to the practices described in this policy.',
    ],
  },
  {
    title: '2. Information We Collect',
    paragraphs: [
      'We collect information you provide directly, information generated by your use of the platform, and information from third-party services where applicable.',
    ],
    items: [
      'Account Information: Your name, username, email address, and password when you register.',
      'Profile Information: Profile photo, bio, and any other information you choose to add to your public profile.',
      'Creator Profile Information: Headline, bio, website, bank name, account number, and account name provided when setting up a creator profile for payout purposes.',
      'Payment Information: Transaction amounts, Paystack payment references, and enrollment financial records. We do not store your card details — all card processing is handled by Paystack.',
      'Payout Information: Bank account details, Paystack subaccount codes, and transfer references associated with creator payouts.',
      'Learning Activity: Courses you enroll in, lessons you complete, progress data, and reviews you submit.',
      'Course Content: If you are a creator, the videos, text, attachments, and other materials you upload to the platform.',
      'Usage Data: Pages visited, features used, time spent, device type, browser, IP address, and referring URLs.',
      'Communications: Messages you send to our support team or through any in-platform communication features. Private messages are end-to-end encrypted and stored as ciphertext only — we cannot access their content.',
      'Encryption Keys: Your public key and an encrypted backup of your wrapped private key, stored solely to enable cross-device access. Your private key is never stored in plaintext on our servers.',
    ],
  },
  {
    title: '3. How We Use Your Information',
    paragraphs: [
      'We use the information we collect to:',
    ],
    items: [
      'Provide, operate, and improve the VibeVista platform',
      'Process course enrollments and payments via Paystack',
      'Facilitate creator payouts to registered bank accounts',
      'Track and display your learning progress and course completion',
      'Send transactional notifications such as enrollment confirmations, course approvals, and payout updates',
      'Verify creator profiles and review course content before publication',
      'Detect and prevent fraud, abuse, and violations of our Terms and Conditions',
      'Respond to support requests and resolve disputes',
      'Comply with applicable legal obligations',
      'Send product updates and promotional communications where you have opted in',
    ],
  },
  {
    title: '4. Sharing Your Information',
    paragraphs: [
      'We do not sell your personal information. We share your data only in the following circumstances:',
    ],
    items: [
      'Paystack: We share payment and payout information with Paystack to process transactions and creator withdrawals. This includes your email address for payment initialisation, and creator bank account details and recipient codes for transfer processing. Paystack\'s privacy policy is available at paystack.com/privacy.',
      'Mux: If you are a creator, video content you upload is processed and stored by Mux for transcoding and streaming. Mux handles video asset IDs and playback on our behalf.',
      'Cloudinary: File attachments uploaded to course lessons are stored and served via Cloudinary.',
      'Service Providers: We may share data with other trusted third-party providers who assist us in operating the platform, subject to confidentiality obligations.',
      'Legal Requirements: We may disclose information where required by law, court order, or to protect the rights and safety of VibeVista, our users, or the public.',
      'Business Transfers: In the event of a merger, acquisition, or sale of assets, your information may be transferred to the successor entity.',
    ],
  },
  {
    title: '5. Data Retention',
    paragraphs: [
      'We retain your personal information for as long as your account is active or as needed to provide you with our services. If you delete your account, we will remove your personal data within 30 days, except where retention is required by law or for legitimate business purposes such as resolving disputes or preventing fraud.',
      'Creator payout records and enrollment financial data are retained for a minimum of 7 years for accounting and regulatory compliance purposes, even after account deletion.',
      'Private messages are automatically and permanently deleted after 90 days. This deletion is irreversible and applies to all parties in the conversation.',
    ],
  },
  {
    title: '6. Cookies & Tracking',
    paragraphs: [
      'We use cookies and similar tracking technologies to maintain your session, remember your preferences, and analyse usage patterns. You can control cookie settings through your browser, though disabling cookies may affect platform functionality.',
    ],
  },
  {
    title: '7. Data Security',
    paragraphs: [
      'We take the security of your personal data seriously and implement multiple layers of protection across the platform. However, no method of transmission or storage is completely secure, and we cannot guarantee absolute security.',
    ],
    items: [
      'In-Transit Encryption: All data transmitted between your device and our servers is encrypted using HTTPS (TLS). This protects your data from interception during transmission.',
      'Password Security: Passwords are never stored in plaintext. We use bcrypt hashing with a unique salt per user, making stored passwords computationally infeasible to reverse.',
      'Authentication: We use Laravel Sanctum with cookie-based authentication. Session cookies are issued with HttpOnly, Secure, and SameSite flags to mitigate cross-site scripting and request forgery attacks. Only one active session is permitted per user at a time — starting a new session deactivates all previous ones.',
      'End-to-End Encrypted Messaging: Private messages on VibeVista are end-to-end encrypted using the NaCl cryptography library (X25519 key exchange, XSalsa20-Poly1305 encryption). Messages are encrypted on your device before being sent and can only be decrypted by the intended recipient. VibeVista servers store and deliver ciphertext only — we cannot read your messages.',
      'Encryption Key Management: Each user has a cryptographic keypair. Your public key is stored on our servers. Your private key is encrypted on your device using a key derived from your password via PBKDF2 (Web Crypto API) and stored in your browser\'s IndexedDB. An encrypted backup of your wrapped private key is held on our servers solely to enable access from a different device — it cannot be decrypted without your password.',
      'Message Retention: Private messages are automatically and permanently deleted after 90 days. This minimises the amount of communication data held on our servers at any time.',
      'Role-Based Access Control: Access to platform data is governed by role-based permissions. Admin functions are restricted to authorised personnel only, and access to sensitive data such as creator bank details and Paystack codes is further restricted within the admin system.',
      'Data Minimisation: We store only the data necessary to operate the platform. Sensitive data such as card details are never stored by us — all card processing is delegated to Paystack.',
      'Periodic Audits: We conduct regular reviews of our data storage and access practices to ensure that only necessary data is retained and that it is appropriately protected.',
      'Creator Financial Data: Bank account details and Paystack subaccount and recipient codes are stored with restricted access and are used solely for the purpose of processing creator payouts.',
    ],
  },
  {
    title: '8. Your Rights',
    paragraphs: [
      'Depending on your jurisdiction, you may have the following rights regarding your personal data:',
    ],
    items: [
      'Access: Request a copy of the personal data we hold about you.',
      'Correction: Request that we correct inaccurate or incomplete information.',
      'Deletion: Request that we delete your personal data, subject to legal retention requirements.',
      'Portability: Request your data in a structured, machine-readable format.',
      'Objection: Object to the processing of your data for marketing purposes at any time.',
      'Withdrawal of Consent: Where processing is based on consent, you may withdraw it at any time without affecting the lawfulness of prior processing.',
    ],
  },
  {
    title: '9. Children\'s Privacy',
    paragraphs: [
      'VibeVista is not directed at children under the age of 13. We do not knowingly collect personal information from children. If you believe a child has provided us with personal data, please contact us and we will take steps to remove the information promptly.',
    ],
  },
  {
    title: '10. Third-Party Links',
    paragraphs: [
      'The platform may contain links to third-party websites or services, including creator websites listed on their profiles. We are not responsible for the privacy practices of third-party sites and encourage you to review their privacy policies.',
    ],
  },
  {
    title: '11. Changes to This Policy',
    paragraphs: [
      'We may update this Privacy Policy from time to time. We will notify you of significant changes via email or an in-app notice. Continued use of VibeVista after changes take effect constitutes acceptance of the revised policy.',
    ],
  },
]
</script>
